apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  labels:
    app: backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
      app: backend
  template:
    metadata:
      labels:
        tier: backend
        app: backend
    spec:
      containers:
      - name: grpc-hello-world
        image: ardimr/grpc-hello-world:dev
        ports:
        - containerPort: 8080
