apiVersion: v1
kind: Service
metadata:
  name: backend-load-balancer
  namespace: grpc-hello-world
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8080
  type: LoadBalancer